version: "3.9"

services:
  dbpost:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./init_scripts/init2.sql:/docker-entrypoint-initdb.d/init2.sql
    ports:
      - 5432:5432